services:
  bot:
    image: ghcr.io/rowentey/teybot:latest
    container_name: teybot
    ports:
      - "8080:8080"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
    volumes:
      - ./cron_config.json:/cron_config.json
